version: '3.8'
services:
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
  nodejs-environment:
    container_name: nodejs
    build: 
      context: ./nodejs
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 3000:3000
  
